// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLq7AQSTO6n558Sx3yZIdmLaSfSRSCSck',
    appId: '1:302157939052:web:15ab5596bb38da6293b349',
    messagingSenderId: '302157939052',
    projectId: 'chatapp-73050',
    authDomain: 'chatapp-73050.firebaseapp.com',
    storageBucket: 'chatapp-73050.appspot.com',
    measurementId: 'G-SJ3VR4JRVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfRodvxeyvyj__tmtJMgQBEkQCrtvm9ok',
    appId: '1:302157939052:android:138c1be2e1c29a5593b349',
    messagingSenderId: '302157939052',
    projectId: 'chatapp-73050',
    storageBucket: 'chatapp-73050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5DwHXDYjcIKLh-NJx__vodTx56djB0w',
    appId: '1:302157939052:ios:ebfa9df89ce28d1193b349',
    messagingSenderId: '302157939052',
    projectId: 'chatapp-73050',
    storageBucket: 'chatapp-73050.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
